### ISSUE TITLE
Turbo lazy loading not connecting stimulus controller

### ISSUE THREAD

**Issue by humphreyja** [hotwired/turbo#47]
Not sure if this should go on this repo or the stimulus repo but here's the issue I'm running into.

I am loading a turbo frame via 
```erb
<%= turbo_frame_tag "event_list.1", src: events_list_path(page: 1) %>
```

This returns the following frame
```erb
<div data-controller="eventlist">
  <%= render @events %>
</div>
```

And `eventlist_controller.js`

```js
import { Controller } from "stimulus"

export default class extends Controller {
  connect() {
    console.log('Im connected!')
  }
}
```

### Expected Result
When the frame is loaded, "Im connected!" is logged to the console

### Actual Result
*sometimes* it works, but most of the time it does not connect. It seems like if it does successfully connect, then as long as I don't refresh the page it will continue to work. 

I am using the the rails asset pipeline with vanilla javascript.

### Gemfile
```ruby
gem 'turbo-rails', github: 'hotwired/turbo-rails', branch: 'main'
gem 'rails', '~> 6.1.0', '>= 6.1.0.0'
gem 'hotwire-rails'
```

**Comment by humphreyja** [comment]
Continued to play with this. It looks like if a stimulus controller does not have any instances to connect to outside of the lazy loaded turbo frames, it will not work. BUT, if I have at least one instance of it defined outside of the lazy frame, then it works as expected. So as a workaround for the time being, I just create "empty" connections to any stimulus controller outside of the lazy frames.

### Example:

```erb
<!-- controllers used in lazy frames -->
<div data-controller="eventlist"></div>

<%= turbo_frame_tag "event_list.1", src: events_list_path(page: 1) %>

```

**Comment by dhh** [comment]
Fix to this is coming to stimulus or stimulus-rails where we'll use a mutation observer so it'll work on frame loads.

**Comment by kstratis** [comment]
Awesome! Any news on this?

**Comment by dhh** [comment]
This has been fixed in latest stimulus-rails.

**Comment by etcook** [comment]
I'm on the latest version (0.2.3) of stimulus-rails and still running into this issue.

**Comment by jameshclrk** [comment]
I'm using Turbo and Stimulus in a non-rails app and have this problem.

What is the best way to approach this problem in a general way?

**Comment by foucist** [comment]
I was forced to use this trick, I'm on stimulus-rails 1.0.4.  

I made a 2-step login with the email field and password field on separate forms, the whole thing is in a frame tag with target "_top" because I needed to show the flash message & change the page when sign in is successful.  So I had to use turbo streams for the actual form swapping part, actually the forms post to the same place, I just check if submit == 'continue' or 'log in'.

**Comment by leoplct** [comment]
I still having this issue stimulus-rails (1.0.4)

**Gemfile**
gem 'hotwire-rails'
gem 'turbo-rails', '>= 1.1.1', :git => 'https://github.com/hotwired/turbo-rails'
gem 'stimulus-rails'

**Comment by dperrymorrow** [comment]
> I'm using Turbo and Stimulus in a non-rails app and have this problem.
> What is the best way to approach this problem in a general way?

Has there been any resolution to this? 
I am using Stimulus + Turbo in a non Rails app and am having the same issue of Stimulus controllers not connecting within a `<turbo-frame>` response

**Comment by oleg-andreyev** [comment]
I'm too using Stimulus + Turbo (via https://github.com/symfony/ux) and having the same situation, controller is not connected when it's lazy loaded via turbo-frame.

**Comment by wakproductions** [comment]
> Never mind. Restated Browser and everything is working 😂

I just encountered the same issue. Browser restart solved it. I find that a bit concerning - not sure why the browser restart mattered.
